log_level: debug

http:
  port: 8080
  gin_mode: debug

auth:
  secret: nx5iZBiUqbYEUmzfV5Se
  password: keeper43


log:
  update_frequency: 5
  dir: ./logs
  retention: 604800 #1 week in seconds
  chunk_size: 1048576 #1 MB in bytes