log_level: debug

http:
  port: 3010
  gin_mode: debug

auth:
  secret: nx5iZBiUqbYEUmzfV5Se
  password: keeper43

log:
  update_frequency: 5
  retention: 604800 #1 week in seconds

db:
  db_file: ./logs.db
  log: false