definitions:
  entity.ContainerInfo:
    properties:
      isAlive:
        type: boolean
      shortName:
        type: string
    type: object
  handler.AuthRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handler.GenericResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  handler.GetContainersResponse:
    properties:
      containers:
        items:
          $ref: '#/definitions/entity.ContainerInfo'
        type: array
    type: object
  handler.SearchLogsResponse:
    properties:
      records:
        items:
          type: string
        type: array
    type: object
  log.GetLinesResponse:
    properties:
      chunkNumber:
        type: integer
      offset:
        type: integer
      records:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /api/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: Input model
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handler.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GenericResponse'
      tags:
      - auth
  /api/container:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GetContainersResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GenericResponse'
      tags:
      - container
  /api/container/{shortname}/log:
    get:
      consumes:
      - application/json
      parameters:
      - description: container's short name
        in: path
        name: shortname
        required: true
        type: string
      - description: number of chunk
        in: query
        name: chunk_number
        type: integer
      - description: offset in chunk
        in: query
        name: offset
        type: integer
      - description: limit of result lines
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/log.GetLinesResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GenericResponse'
      tags:
      - log
  /api/container/{shortname}/log/search:
    get:
      consumes:
      - application/json
      parameters:
      - description: container's short name
        in: path
        name: shortname
        required: true
        type: string
      - description: contains substring
        in: query
        name: contains
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SearchLogsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.GenericResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.GenericResponse'
      tags:
      - log
swagger: "2.0"
